### ISSUE TITLE
TF2.5 - Implementar a automatização de coleta e deploy dos dados para a API

### ISSUE THREAD

**Issue by GeovanaRamos** [ads-unigrade-2019-1/MWScanner#5]
## Implementar a automatização de coleta e deploy dos dados para a API

**Prazo**: 15/04

**Comment by guilherme1guy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploy do Webscraper](https://trello.com/c/xRg3nuzO/6-deploy-do-webscraper)
